# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8a4323e75d3413646a029832b7f709033d790f8e6f2e1e24ca2701cdc977c7c3c55b8bed129045c37b3d93da49e0d08255d28415c17a084a1d5a715236f2202

test:
  secret_key_base: d53edaa8ac702e7c794eb110c77a03d4683d71a929c57ed17a1960af2eab7690d717e56ba089f7b27b6f788da7b6d39a3ceb8fba6e740d73885be480ab663794

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
